pie title Lines of Code by Module
    "config" : 58
    "types" : 45
    "render" : 67
    "source" : 141
    "viewer" : 74
    "display" : 80
    "kitty" : 90
    "navigation" : 139
    "init" : 100
    "debounce" : 47
    "state" : 32
    "temp" : 36
